# Generated by Django 6.0.6 on 2026-06-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(choices=[('PLASTIC', 'Pollution plastique'), ('EROSION', 'Érosion côtière'), ('WASTE', 'Déchets sauvages'), ('FLOOD', 'Inondation'), ('WATER', "Pollution de l'eau"), ('AIR', "Pollution de l'air"), ('OTHER', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alerts/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
