# Generated by Django 6.0.6 on 2026-06-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
