# Generated by Django 6.0.6 on 2026-06-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('EROSION', 'Érosion côtière'), ('PLASTIC', 'Pollution plastique'), ('EVENT', 'Événement'), ('REPORTAGE', 'Reportage'), ('BIODIVERSITY', 'Biodiversité'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
