# Generated by Django 6.0.6 on 2026-06-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('YOUTUBE', 'YouTube')], default='IMAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('EROSION', 'Érosion côtière'), ('PLASTIC', 'Pollution plastique'), ('EVENT', 'Événement'), ('REPORTAGE', 'Reportage'), ('BIODIVERSITY', 'Biodiversité'), ('INTERVIEW', 'Interview'), ('OTHER', 'Autre')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/images/'),
        ),
    ]
